### ISSUE TITLE
`notification_url` do I need to check the signature?

### ISSUE THREAD

**Issue by AlexStef** [payplug/payplug-php#7]
Hello,

In the following documentation , it is said to check the signature in our notification endpoint to ensure authorization.
[http://payplug-developer-documentation.readthedocs.io/en/latest/#instant-payment-notification-ipn](http://payplug-developer-documentation.readthedocs.io/en/latest/#instant-payment-notification-ipn)

In the PHP Example on the following link, this endpoint uses "as is" the payment resource to check if it's paid. The resource could be wrong and forged by someone else, couldn't it ?
[https://www.payplug.com/docs/api/apiref.html#notifications](https://www.payplug.com/docs/api/apiref.html#notification)s
I noticed I could fake a payment notification by sending a request manually to my endpoint. 

My question is : do I need to check the signature ? If yes, I don't see in the request headers any `PAYPLUG-SIGNATURE` value.

Thank you in advance

**Comment by nilleroux** [comment]
Hi,

The first link you provided referers to the deprecated API. This API indeed provides a signature for the resource.

In the new API (second link you provided), no signature is provided any longer. If you want to authenticate the resource (which is probably almost always the case), you must perform a new GET request to the API endpoint.
This library provides an easy way to do this, using the Notification::treat method. Since the resource returned by this method comes from an API call, you can actually trust it. You will be able to find an implementation example in the second link you provided.

Please, let me know if this answers your question. Anyways, thank you very much for your feedback and contribution. We really appreciate.
Regards,
Nils

**Comment by AlexStef** [comment]
Hi Nils, thanks for thé fast answer!

That is exactly what I thought about the deprecated doc, but I wanted to be sure.

Getting the resource with a GET request from my endpoint is what i did , not seeing any other way ; so this is perfect!
The request is authenticated, everything's fine.

Thank you again ! (Maybe a word about this in the doc ? Or maybe it's obvious)

**Comment by nilleroux** [comment]
Glad it helped you out :-). We'll look into making this clearer in the doc in the future.
Thank you.
